package no.lebegue.christophe.FarmMgmt.Controller;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import no.lebegue.christophe.FarmMgmt.Entity.Activity;
import no.lebegue.christophe.FarmMgmt.Entity.ActivityRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/activities") // This means URL's start with /demo (after Application path)
public class ActivityController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ActivityRepository repository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewActivity (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Activity n = new Activity();
		n.setName(name);
		repository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Activity> getAllActivities() {
		// This returns a JSON or XML with the users
		return repository.findAll();
	}
}